services:
  redeployment-service:
    build: .
    ports:
      - "5.78.108.80:3000:3000"
    user: "${UID:-1000}:${GID:-1000}"  # Run as the same user as the host
    volumes:
      # Mount SSH keys for GitHub access
      - ~/.ssh:/home/node/.ssh:ro
      # Mount apps directory (parent directory of redeployment-service)
      - ~/apps:/apps:rw
      # Mount Docker socket for Docker operations
      - /var/run/docker.sock:/var/run/docker.sock:ro
    environment:
      - NODE_ENV=production
    env_file:
      - .env
    restart: unless-stopped
